import { Providers } from "@/redux/provider";
import "./globals.css";
import type { Metadata } from "next";
import { Oswald } from "next/font/google";

const oswal = Oswald({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={oswal.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
